Rezolvare erori

diff --git a/activeaza_venv_jenkins b/activeaza_venv_jenkins
--- a/activeaza_venv_jenkins
+++ b/activeaza_venv_jenkins
@@ -1,11 +1,14 @@
-echo "Trying to create the venv in the folder: .venv"
-python3 -m venv .venv
-echo "Activating virtual environment"
-# source ../venv/bin/activate
+# venv-ul se gaseste in directorul parinte: .venv
+# source ../.venv/bin/activate
 . .venv/bin/activate
-echo "Installing the dependencies"
 
-
-# sau prin intermediul fisierului de requirements
-pip install -r quickrequirements.txt
+# daca comanda de mai sus esueaza, creaza .venv si instaleaza dependintele
+# venv-ul va ramane activat in acest caz
+if [ $? -eq 0 ]
+then
+    echo "SUCCESS: venv was activated."
+else
+    echo "FAIL: cannot activate venv"
+    . ./activeaza_venv_jenkins
+fi
 
